name: code_checks

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install departments
        run: |
          python -m pip install --upgrade pip
          pip freeze > requirements.txt
      - name: Test with pytest
        run: pytest -vv